export const sidbarData = [
    {
        id: 1,
        listItems: [
            { id: 1, title: 'Create', href: '/create', icon: 'FileEarmarkPlus' },
            { id: 2, title: 'Translation', href: '/translation', icon: 'Translate' },
            { id: 3, title: 'Convert Type', href: '/convert-type', icon: 'FileEarmarkBreak' },
            { id: 4, title: 'Edit', href: '/edit', icon: 'PencilSquare' },
        ]
    },
]

export const languages = [
    { ln: "Afrikaans", value: "af" },
    { ln: "Albanian", value: "sq" },
    { ln: "Amharic", value: "am" },
    { ln: "Arabic", value: "ar" },
    { ln: "Armenian", value: "hy" },
    { ln: "Assamese", value: "as" },
    { ln: "Aymara", value: "ay" },
    { ln: "Azerbaijani", value: "az" },
    { ln: "Bambara", value: "bm" },
    { ln: "Basque", value: "eu" },
    { ln: "Belarusian", value: "be" },
    { ln: "Bengali", value: "bn" },
    { ln: "Bhojpuri", value: "bho" },
    { ln: "Bosnian", value: "bs" },
    { ln: "Bulgarian", value: "bg" },
    { ln: "Catalan", value: "ca" },
    { ln: "Cebuano", value: "ceb" },
    { ln: "Chinese (Simplified)", value: "zh" },
    { ln: "Chinese (Simplified)", value: "zh-CN" },
    { ln: "Chinese (Traditional)", value: "zh-TW" },
    { ln: "Corsican", value: "co" },
    { ln: "Croatian", value: "hr" },
    { ln: "Czech", value: "cs" },
    { ln: "Danish", value: "da" },
    { ln: "Dhivehi", value: "dv" },
    { ln: "Dogri", value: "doi" },
    { ln: "Dutch", value: "nl" },
    { ln: "English", value: "en" },
    { ln: "Esperanto", value: "eo" },
    { ln: "Estonian", value: "et" },
    { ln: "Ewe", value: "ee" },
    { ln: "Filipino (Tagalog)", value: "fil" },
    { ln: "Finnish", value: "fi" },
    { ln: "French", value: "fr" },
    { ln: "Frisian", value: "fy" },
    { ln: "Galician", value: "gl" },
    { ln: "Georgian", value: "ka" },
    { ln: "German", value: "de" },
    { ln: "Greek", value: "el" },
    { ln: "Guarani", value: "gn" },
    { ln: "Gujarati", value: "gu" },
    { ln: "Haitian Creole", value: "ht" },
    { ln: "Hausa", value: "ha" },
    { ln: "Hawaiian", value: "haw" },
    { ln: "Hebrew", value: "he" },
    { ln: "Hebrew", value: "iw" },
    { ln: "Hindi", value: "hi" },
    { ln: "Hmong", value: "hmn" },
    { ln: "Hungarian", value: "hu" },
    { ln: "Icelandic", value: "is" },
    { ln: "Igbo", value: "ig" },
    { ln: "Ilocano", value: "ilo" },
    { ln: "Indonesian", value: "id" },
    { ln: "Irish", value: "ga" },
    { ln: "Italian", value: "it" },
    { ln: "Japanese", value: "ja" },
    { ln: "Javanese", value: "jw" },
    { ln: "Javanese", value: "jv" },
    { ln: "Kannada", value: "kn" },
    { ln: "Kazakh", value: "kk" },
    { ln: "Khmer", value: "km" },
    { ln: "Kinyarwanda", value: "rw" },
    { ln: "Konkani", value: "gom" },
    { ln: "Korean", value: "ko" },
    { ln: "Krio", value: "kri" },
    { ln: "Kurdish", value: "ku" },
    { ln: "Kurdish (Sorani)", value: "ckb" },
    { ln: "Kyrgyz", value: "ky" },
    { ln: "Lao", value: "lo" },
    { ln: "Latin", value: "la" },
    { ln: "Latvian", value: "lv" },
    { ln: "Lingala", value: "ln" },
    { ln: "Lithuanian", value: "lt" },
    { ln: "Luganda", value: "lg" },
    { ln: "Luxembourgish", value: "lb" },
    { ln: "Macedonian", value: "mk" },
    { ln: "Maithili", value: "mai" },
    { ln: "Malagasy", value: "mg" },
    { ln: "Malay", value: "ms" },
    { ln: "Malayalam", value: "ml" },
    { ln: "Maltese", value: "mt" },
    { ln: "Maori", value: "mi" },
    { ln: "Marathi", value: "mr" },
    { ln: "Meiteilon (Manipuri)", value: "Mtei" },
    { ln: "Meiteilon (Manipuri)", value: "mni" },
    { ln: "Mizo", value: "lus" },
    { ln: "Mongolian", value: "mn" },
    { ln: "Myanmar (Burmese)", value: "my" },
    { ln: "Norwegian", value: "no" },
    { ln: "Nyanja (Chichewa)", value: "ny" },
    { ln: "Nepali", value: "ne" },
    { ln: "Odia (Oriya)", value: "or" },
    { ln: "Oromo", value: "om" },
    { ln: "Pashto", value: "ps" },
    { ln: "Persian", value: "fa" },
    { ln: "Polish", value: "pl" },
    { ln: "Portuguese (Portugal, Brazil)", value: "pt" },
    { ln: "Punjabi", value: "pa" },
    { ln: "Quechua", value: "qu" },
    { ln: "Romanian", value: "ro" },
    { ln: "Russian", value: "ru" },
    { ln: "Samoan", value: "sm" },
    { ln: "Sanskrit", value: "sa" },
    { ln: "Scots Gaelic", value: "gd" },
    { ln: "Sepedi", value: "nso" },
    { ln: "Serbian", value: "sr" },
    { ln: "Sesotho", value: "st" },
    { ln: "Shona", value: "sn" },
    { ln: "Sindhi", value: "sd" },
    { ln: "Sinhala (Sinhalese)", value: "si" },
    { ln: "Slovak", value: "sk" },
    { ln: "Slovenian", value: "sl" },
    { ln: "Somali", value: "so" },
    { ln: "Spanish", value: "es" },
    { ln: "Sundanese", value: "su" },
    { ln: "Swahili", value: "sw" },
    { ln: "Swedish", value: "sv" },
    { ln: "Tagalog (Filipino)", value: "tl" },
    { ln: "Tajik", value: "tg" },
    { ln: "Tamil", value: "ta" },
    { ln: "Tatar", value: "tt" },
    { ln: "Telugu", value: "te" },
    { ln: "Thai", value: "th" },
    { ln: "Tigrinya", value: "ti" },
    { ln: "Tsonga", value: "ts" },
    { ln: "Turkish", value: "tr" },
    { ln: "Turkmen", value: "tk" },
    { ln: "Twi (Akan)", value: "ak" },
    { ln: "Ukrainian", value: "uk" },
    { ln: "Urdu", value: "ur" },
    { ln: "Uyghur", value: "ug" },
    { ln: "Uzbek", value: "uz" },
    { ln: "Vietnamese", value: "vi" },
    { ln: "Welsh", value: "cy" },
    { ln: "Xhosa", value: "xh" },
    { ln: "Yiddish", value: "yi" },
    { ln: "Yoruba", value: "yo" },
    { ln: "Zulu", value: "zu" },
];

export const colors = [
    '#F44336',
    '#FF5722',
    '#FF9800',
    '#FFAB40',
    '#FFC107',
    '#FFEB3B',
    '#CDDC39',
    '#8BC34A',
    '#4CAF50',
    '#00BFA5',
    '#009688',
    '#8ED1FC',
    '#2196F3',
    '#3F51B5',
    '#006064',
    '#673AB7',
    '#9C27B0',
    '#D1C4E9',
    '#E91E63',
    '#FF4081',
    '#F78DA7',
    '#795548',
    '#607D8B',
    '#000000'
];

export const types = [
    { name: 'WebVTT(vtt)', value: 'vtt' },
    { name: 'SubRip(srt)', value: 'srt' },
    { name: 'SubViewer(sub)', value: 'sub' },
]